import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const EnvConfig = createEnv({
    server: {
        BACKEND_ENDPOINT: z.url(),
    },
    client: {
        NEXT_PUBLIC_BETTER_AUTH_ENDPOINT: z.url(),
        NEXT_PUBLIC_PAGINATION_PAGE_MOBILE_SIZE: z.coerce.number(),
        NEXT_PUBLIC_PAGINATION_LIMIT_MOBILE_SIZE: z.coerce.number(),
        NEXT_PUBLIC_PAGINATION_PAGE_DESKTOP_SIZE: z.coerce.number(),
        NEXT_PUBLIC_PAGINATION_LIMIT_DESKTOP_SIZE: z.coerce.number(),
    },
    runtimeEnv: {
        BACKEND_ENDPOINT: process.env.BACKEND_ENDPOINT,
        NEXT_PUBLIC_BETTER_AUTH_ENDPOINT: process.env.NEXT_PUBLIC_BETTER_AUTH_ENDPOINT,
        NEXT_PUBLIC_PAGINATION_PAGE_MOBILE_SIZE: process.env.NEXT_PUBLIC_PAGINATION_PAGE_MOBILE_SIZE,
        NEXT_PUBLIC_PAGINATION_LIMIT_MOBILE_SIZE: process.env.NEXT_PUBLIC_PAGINATION_LIMIT_MOBILE_SIZE,
        NEXT_PUBLIC_PAGINATION_PAGE_DESKTOP_SIZE: process.env.NEXT_PUBLIC_PAGINATION_PAGE_DESKTOP_SIZE,
        NEXT_PUBLIC_PAGINATION_LIMIT_DESKTOP_SIZE: process.env.NEXT_PUBLIC_PAGINATION_LIMIT_DESKTOP_SIZE,
    }
});
